
default_platform(:android)

platform :android do
  desc "For firebase app distribution"
  lane :firebase_distribution do
      sh "flutter clean"
      sh "flutter build apk --release"
     firebase_app_distribution(
                app: ENV["APP_TOKEN"],
                firebase_cli_token:ENV["FIREBASE_CLI_TOKEN"],
                testers: "awais@covalent.global",
                android_artifact_path: "../build/app/outputs/apk/release/app-release.apk",
                release_notes: "App is distributed via fastlane"
            )
  end
end
